### ISSUE TITLE
all examples fail on Raspberry Pi Zero with Buster Lite

### ISSUE THREAD

**Issue by cipy** [google-coral/edgetpu-platforms#31]
with

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'edgetpu.swig._edgetpu_cpp_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify_image.py", line 19, in <module>
    from edgetpu.classification.engine import ClassificationEngine
  File "/usr/local/lib/python3.7/dist-packages/edgetpu/classification/engine.py", line 17, in <module>
    from edgetpu.basic.basic_engine import BasicEngine
  File "/usr/local/lib/python3.7/dist-packages/edgetpu/basic/basic_engine.py", line 15, in <module>
    from edgetpu.swig.edgetpu_cpp_wrapper import BasicEngine
  File "/usr/local/lib/python3.7/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 21, in <module>
    _edgetpu_cpp_wrapper = swig_import_helper()
  File "/usr/local/lib/python3.7/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 20, in swig_import_helper
    return importlib.import_module('_edgetpu_cpp_wrapper')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_edgetpu_cpp_wrapper'
```

this is Buster Lite on RPi Zero W

The examples do work on rpi0-raspbian-stretch-edgetpu-1.9.2.img.gz (ancient OS image)

**Comment by Namburger** [comment]
@cipy 
It's worth mentioning that this is an **unofficial** platform that we create to make earlier versions of our software easier for beginners with rpi. It is very hard to maintain this repo right now since our software stack grows far beyond jut rpi users. Also it is not a popular request anymore. 
The last image contains a very old version of libedgetpu runtime (11). We are now at 14, you should be able to easily use the accelerator with the getting started page: https://coral.ai/docs/accelerator/get-started

Please also check requirement section: https://coral.ai/docs/accelerator/get-started/#requirements

**Comment by cipy** [comment]
Thanks @Namburger 

I'll try it later on RPi 3B+ and 4B

The biggest advantage with supporting RPi Zero is that Zero is very good for edge computing

**Comment by Namburger** [comment]
@cipy I see, I guess we moved away from pi0 because lack of demand. 
But anyhow, this image should works for the pi0 in theory, it'll just be running an older version of our library and we'll soon drop supports for older version of python. 
I remember seeing issues like this with our older releases but it's so long ago :)
Would something like this answer: https://github.com/google-coral/edgetpu-platforms/issues/10#issuecomment-509025130 help?

**Comment by zamathebest** [comment]
Hi, same issue with the RPi0-W using Raspbian Buster
May you share the makefile and Dockerfile used to compile the edgetpu for RPi0?

**Comment by hjonnala** [comment]
Closing   the  issue since the edgetpu is deprecated and due to lack of official support for Raspberry Pi Zero. Sorry for the inconvenience.
